name: 'MLL With Integration Tests'
on: 'workflow_dispatch'
jobs:
  mll:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: 'Apply Workflow Patches'
      run: |
        cd .github
        bash ./github-ci.sh
    - name: 'Build Minimal Linux Live'
      run: |
        cd .github
        bash ./build_mll.sh
    - name: 'Test Docker'
      run: |
        cd .github
        bash ./test_docker.sh
    - name: 'Test QEMU'
      run: |
        cd .github
        bash ./test_qemu.sh
